tasks:
  - name: Azure CLI
    init: |
      brew update && brew install azure-cli
    command: |
      az login --use-device-code
      az account set --subscription "datagriff Teaching"
      az account show
      gp sync-done waitonazurecli
  - name: Terraform
    init: |
      brew tap hashicorp/tap
      brew install hashicorp/tap/terraform
    command: |
      gp sync-await waitonazurecli
      cd  terraform
      terraform init
      terraform fmt
      terraform validate
      terraform plan

vscode:
  extensions:
    - hashicorp.terraform